// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw_kFhGwLI8NvT51NJJstnJgbn7fGVcMs',
    appId: '1:1073000628426:web:ca89e274bed0b0062bf433',
    messagingSenderId: '1073000628426',
    projectId: 'kiosk-8b28a',
    authDomain: 'kiosk-8b28a.firebaseapp.com',
    storageBucket: 'kiosk-8b28a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjZ6XCLfoKUKt1gLYI4OOLm0yYA81-nYk',
    appId: '1:1073000628426:android:50c20bb56c06a7202bf433',
    messagingSenderId: '1073000628426',
    projectId: 'kiosk-8b28a',
    storageBucket: 'kiosk-8b28a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3AUTCE4lb1JT5WbsHgChJsIYHPzV45Ws',
    appId: '1:1073000628426:ios:39b7a45957ac4a232bf433',
    messagingSenderId: '1073000628426',
    projectId: 'kiosk-8b28a',
    storageBucket: 'kiosk-8b28a.firebasestorage.app',
    iosBundleId: 'com.example.kioskFcsit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3AUTCE4lb1JT5WbsHgChJsIYHPzV45Ws',
    appId: '1:1073000628426:ios:39b7a45957ac4a232bf433',
    messagingSenderId: '1073000628426',
    projectId: 'kiosk-8b28a',
    storageBucket: 'kiosk-8b28a.firebasestorage.app',
    iosBundleId: 'com.example.kioskFcsit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw_kFhGwLI8NvT51NJJstnJgbn7fGVcMs',
    appId: '1:1073000628426:web:8ee0865721e3f1702bf433',
    messagingSenderId: '1073000628426',
    projectId: 'kiosk-8b28a',
    authDomain: 'kiosk-8b28a.firebaseapp.com',
    storageBucket: 'kiosk-8b28a.firebasestorage.app',
  );
}
