// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSgX0b_UEfiiKHGvMB2veuPrL24S0tatI',
    appId: '1:818831202140:web:12de0cb19a67c2724c5399',
    messagingSenderId: '818831202140',
    projectId: 'kiosk-fcsit',
    authDomain: 'kiosk-fcsit.firebaseapp.com',
    storageBucket: 'kiosk-fcsit.firebasestorage.app',
    measurementId: 'G-6L6QKX9ZKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwM4bUY4etJP2DNUabGdf29cf58W_4sdY',
    appId: '1:818831202140:android:28d3faa32149043d4c5399',
    messagingSenderId: '818831202140',
    projectId: 'kiosk-fcsit',
    storageBucket: 'kiosk-fcsit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIby4v7Se8v_BigUdZu0eYqd-r3QqzqZA',
    appId: '1:818831202140:ios:c00bc65d4a1397be4c5399',
    messagingSenderId: '818831202140',
    projectId: 'kiosk-fcsit',
    storageBucket: 'kiosk-fcsit.firebasestorage.app',
    iosBundleId: 'com.example.networkclanKioskFcsitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIby4v7Se8v_BigUdZu0eYqd-r3QqzqZA',
    appId: '1:818831202140:ios:c00bc65d4a1397be4c5399',
    messagingSenderId: '818831202140',
    projectId: 'kiosk-fcsit',
    storageBucket: 'kiosk-fcsit.firebasestorage.app',
    iosBundleId: 'com.example.networkclanKioskFcsitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSgX0b_UEfiiKHGvMB2veuPrL24S0tatI',
    appId: '1:818831202140:web:7c934408764534f54c5399',
    messagingSenderId: '818831202140',
    projectId: 'kiosk-fcsit',
    authDomain: 'kiosk-fcsit.firebaseapp.com',
    storageBucket: 'kiosk-fcsit.firebasestorage.app',
    measurementId: 'G-WRQN04GBBG',
  );
}
